/*
 * Copyright (C) 2018-2019
 */

#ifndef LOG_COMMON_H
#define LOG_COMMON_H

enum log_level
{
	LOG_LEVEL_DISABLED = 0,
	LOG_LEVEL_TRACE = 1,
	LOG_LEVEL_DEBUG = 2,
	LOG_LEVEL_INFO = 3,
	LOG_LEVEL_WARN = 4,
	LOG_LEVEL_ERROR = 5,
	LOG_LEVEL_FATAL = 6,

	NUM_ENABLED_LOG_LEVELS = 6
};

enum appender_type : uint8_t
{
	APPENDER_NONE,
	APPENDER_CONSOLE,
	APPENDER_FILE,
	APPENDER_DB
};

enum appender_flags
{
	APPENDER_FLAGS_NONE = 0x00,
	APPENDER_FLAGS_PREFIX_TIMESTAMP = 0x01,
	APPENDER_FLAGS_PREFIX_LOGLEVEL = 0x02,
	APPENDER_FLAGS_PREFIX_LOGFILTERTYPE = 0x04,
	APPENDER_FLAGS_USE_TIMESTAMP = 0x08, // 只有file_appender使用
	APPENDER_FLAGS_MAKE_FILE_BACKUP = 0x10  // 只有file_appender使用
};

#endif
